global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
- name: 'web.hook'
  webhook_configs:
    - url: 'http://10.7.5.190:5001/webhook' # office
# change to your local ip address!
# - url: 'http://192.168.1.57:5001/webhook'
