alabaster==0.7.16
ansible==9.3.0
ansible-core==2.16.4
attrs==23.2.0
awxkit==24.1.0
Babel==2.14.0
bcrypt==4.1.2
blinker==1.7.0
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
cryptography==42.0.5
distro==1.9.0
docker==6.1.3
docker-compose==1.29.2
dockerpty==0.4.1
docopt==0.6.2
docutils==0.20.1
Flask==3.0.2
idna==3.6
imagesize==1.4.1
itsdangerous==2.1.2
Jinja2==3.1.3
jsonschema==3.2.0
MarkupSafe==2.1.5
packaging==24.0
paramiko==3.4.0
pycparser==2.21
Pygments==2.17.2
PyNaCl==1.5.0
pyrsistent==0.20.0
python-dotenv==0.21.1
PyYAML==5.3.1
requests==2.31.0
resolvelib==1.0.1
six==1.16.0
snowballstemmer==2.2.0
Sphinx==7.2.6
sphinxcontrib-applehelp==1.0.8
sphinxcontrib-autoprogram==0.1.9
sphinxcontrib-devhelp==1.0.6
sphinxcontrib-htmlhelp==2.0.5
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.7
sphinxcontrib-serializinghtml==1.1.10
texttable==1.7.0
urllib3==2.2.1
websocket-client==0.59.0
Werkzeug==3.0.1
