global:
  scrape_interval: 15s

# Add the Alertmanager configuration below the 'global' section
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - '10.5.0.6:9093'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - '10.5.0.5:9090'

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['34.125.43.194:9100']

  - job_name: 'ssh_probe'
    metrics_path: /probe
    params:
      module: [ssh_banner]  # This should match the module name in blackbox.yml
    static_configs:
      - targets:
        - '34.125.43.194:22'  # Target for SSH probing
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: '10.5.0.7:9115'  # Ensure this matches the Blackbox Exporter's service name and port in docker-compose.yml

  - job_name: 'http_probe'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - '34.125.43.194:80'  # Replace with your VM's IP and the HTTP port
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox_exporter:9115'  # The Blackbox Exporter's address

rule_files:
  - "rules/*.yml"
